server:
  port: 8081
spring:
  application:
    name: demo
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.185.191:8848
  datasource:
    url: jdbc:mysql://47.106.185.191:3306/user?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
fdfs:
  so-timeout: 1501  # 超时时间
  connect-timeout: 601  # 连接超时时间
  thumb-image:  # 缩略图
    width: 60
    height: 60
  tracker-list:  # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 47.106.185.191:22122
  ret-post: 47.106.185.191:22000
my:
  thread:
    core-size: 10
    max-size: 20
    keep-alive-time: 200
