server:
  port: 8080
spring:
  application:
    name: gateway8080
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://demo #匹配后提供服务的路由地址
          predicates:
            - Path=/test/**
    nacos:
      discovery:
        server-addr: 47.106.185.191:8848